name: Docker Image CI Pull

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
        os: [linux]
        service:
          - name: runtime:0.1.1
          - name: muagent:0.1.1
          - name: ekgfrontend:0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          # 登录阿里云镜像仓库 (成都地域)
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} crpi-6pnfau7kx5q4ttr8.cn-chengdu.personal.cr.aliyuncs.com

          # 拉取 ghcr.io 的镜像
          docker pull --platform ${{ matrix.os }}/${{ matrix.architecture }}  ghcr.io/codefuse-ai/${{ matrix.service.name }}
          
          # 使用【正确】的成都地域地址为镜像打标签
          docker tag ghcr.io/codefuse-ai/${{ matrix.service.name }} crpi-6pnfau7kx5q4ttr8.cn-chengdu.personal.cr.aliyuncs.com/jmuagent/${{ matrix.service.name }}-${{ matrix.architecture }}
          
          # 推送镜像到【正确】的成都地域仓库
          docker push crpi-6pnfau7kx5q4ttr8.cn-chengdu.personal.cr.aliyuncs.com/jmuagent/${{ matrix.service.name }}-${{ matrix.architecture }}
